language: python
python: 2.7

env:
  - TOXENV=py26
  - TOXENV=py27

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

before_script:
  - mkdir -p log

script:
  - tox

after_script:
  - rm -rf log

after_success:
  - pip install coveralls
  - coveralls
